[package]
name = "loading"
version = "0.1.0"
edition = "2024"

[dependencies]
bevy.workspace = true
states.workspace = true
portal_assets.workspace = true
research.workspace = true
unlocks.workspace = true
unlocks_assets.workspace = true
wallet.workspace = true
village_components.workspace = true
