[package]
name = "crafting_ui"
version = "0.1.0"
edition = "2024"

[dependencies]
bevy.workspace = true
crafting_resources.workspace = true
wallet.workspace = true
states.workspace = true
research.workspace = true
widgets.workspace = true
