[package]
name = "forsaken_lands"
version = "0.1.0"
edition = "2024"

[workspace]
members= ["wallet", "core", "village", "portals"]

[workspace.dependencies]
bevy = "0.17"

[dependencies]
bevy.workspace = true
core = { path = "core" }
