[package]
name = "forsaken_lands"
version = "0.1.0"
edition = "2024"

[workspace]
members = [
  "components/enemy_components",
  "components/portal_components",
  "components/village_components",
  "components/wallet_components",
  "core",
  "game_assets",
  "portals",
  "states",
  "system_schedule",
  "village",
  "wallet",
]

[workspace.dependencies]
bevy = "0.17"
core = { path = "core" }
enemy_components = { path = "components/enemy_components" }
game_assets = { path = "game_assets" }
portal_components = { path = "components/portal_components" }
portals = { path = "portals" }
states = { path = "states" }
system_schedule = { path = "system_schedule" }
village = { path = "village" }
village_components = { path = "components/village_components" }
wallet = { path = "wallet" }
wallet_components = { path = "components/wallet_components" }

[dependencies]
bevy.workspace = true
core.workspace = true
states.workspace = true
