[package]
name = "portal_assets"
version = "0.1.0"
edition = "2024"

[dependencies]
bevy.workspace = true
divinity_components.workspace = true
serde.workspace = true
bevy_common_assets.workspace = true
