[package]
name = "unlocks"
version = "0.1.0"
edition = "2024"

[dependencies]
bevy.workspace = true
serde.workspace = true
unlocks_assets.workspace = true
unlocks_components.workspace = true
unlocks_events.workspace = true
unlocks_resources.workspace = true
