[package]
name = "portals"
version = "0.1.0"
edition = "2024"

[dependencies]
bevy.workspace = true
portal_components = { path = "../components/portal_components" }
game_assets = { path = "../game_assets" }
states = { path = "../states" }
