[package]
name = "core"
version = "0.1.0"
edition = "2024"

[dependencies]
bevy.workspace = true
states.workspace = true
village.workspace = true
portals.workspace = true
wallet.workspace = true
game_assets.workspace = true
system_schedule.workspace = true
