[package]
name = "core"
version = "0.1.0"
edition = "2024"

[dependencies]
bevy.workspace = true
states.workspace = true
village = { path = "../village" }
portals = { path = "../portals" }
wallet = { path = "../wallet" }
game_assets.workspace = true
