[package]
name = "blessings_ui"
version = "0.1.0"
edition = "2024"

[dependencies]
bevy.workspace = true
widgets.workspace = true
wallet.workspace = true
blessings = { path = "../../blessings" }
growth = { path = "../../growth" }
states = { path = "../../states" }
