[package]
name = "portal_resources"
version = "0.1.0"
edition = "2024"

[dependencies]
bevy.workspace = true
divinity_components.workspace = true
serde = { version = "1.0", features = ["derive"] }
bevy_common_assets = { version = "0.14", features = ["ron"] }
