[package]
name = "unlocks_assets"
version = "0.1.0"
edition = "2024"

[dependencies]
bevy.workspace = true
bevy_common_assets = { workspace = true, features = ["ron"] }
serde = { version = "1", features = ["derive"] }
unlocks_components.workspace = true
