[package]
name = "bonus_stats_assets"
version = "0.1.0"
edition = "2024"

[dependencies]
bevy.workspace = true
serde.workspace = true
bonus_stats_resources.workspace = true
unlocks_assets.workspace = true
