[package]
name = "research_ui"
version = "0.1.0"
edition = "2024"

[dependencies]
bevy.workspace = true
research.workspace = true
wallet.workspace = true
states.workspace = true
widgets.workspace = true
research_assets.workspace = true
