[package]
name = "village"
version = "0.1.0"
edition = "2024"

[dependencies]
bevy.workspace = true
village_components = { path = "../components/village_components" }
game_assets = { path = "../game_assets" }
states = { path = "../states" }
