[package]
name = "crafting"
version = "0.1.0"
edition = "2024"

[dependencies]
bevy.workspace = true
crafting_events.workspace = true
crafting_resources.workspace = true
states.workspace = true
system_schedule.workspace = true
