[package]
name = "enemy_encyclopedia"
version = "0.1.0"
edition = "2024"

[dependencies]
bevy.workspace = true
states.workspace = true
village_components.workspace = true
widgets.workspace = true
enemy_resources.workspace = true
wallet.workspace = true
bonus_stats_resources.workspace = true
